apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
    name: document-database
    namespace: quarkus-playground
spec:
    databaseCpu: 30m
    databaseCpuLimit: 60m
    databaseMemoryLimit: 512Mi
    databaseMemoryRequest: 128Mi
    databaseName: document-database
    databaseNameKeyEnvVar: POSTGRESQL_DATABASE
    databasePassword: admin
    databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
    databaseStorageRequest: 1Gi
    databaseUser: admin
    databaseUserKeyEnvVar: POSTGRESQL_USER
    image: centos/postgresql-96-centos7
    size: 1
