apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: documents
  labels:
    strimzi.io/cluster: mini-kafka
  namespace: quarkus-playground
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
