CREATE ROLE admin WITH LOGIN PASSWORD 'admin';

CREATE ROLE document_admin WITH LOGIN PASSWORD 'document_password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE document_database;
GRANT ALL PRIVILEGES ON DATABASE document_database TO document_admin ;
GRANT ALL PRIVILEGES ON DATABASE document_database TO admin;